### ISSUE TITLE
FirebaseApp has to define a valid projectId

### ISSUE THREAD

**Issue by TheRohitSharma** [hoxfon/react-native-twilio-programmable-voice#149]
Please include the following information for better support

The more context you provide around this issue the faster the community can help you

Did you follow all the instructions as specified in the Twilio Quickstart repositories? Yes
What version of React Native are you running? 0.61.2
What version of react-native-twilio-programmable-voice are you running? 3.21.3
What device are you using? (e.g iOS10 simulator, Android 7 device)? Simulator and Device
Is your app running in foreground, background or not running? foreground
Is there any relevant message in the log? Yes
If using iOS, which pod version are you using? N/A

Step to reproduce
Use `TwilioVoice.initWithToken(token)`

Advanced:
Have you tried adding break point using AndroidStudio or XCode and analyse the logs? Yes
can share a project with issue? No
Did you try to reinstall the pods completely? N/A

Everything was working for me before, but suddenly my app crashes once it gets to`TwilioVoice.initWithToken(token)`. Here's what I get:

<img width="309" alt="Screen Shot 2020-03-30 at 8 47 34 PM" src="https://user-images.githubusercontent.com/9807835/77978420-bb05cf80-72c7-11ea-9081-5f3ad4225381.png">

```
03-30 20:43:22.776  7622  7775 D RNTwilioVoice: initWithAccessToken ACTION_FCM_TOKEN
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: Exception in native call
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: java.lang.IllegalArgumentException: FirebaseApp has to define a valid projectId.
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:8)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at com.google.firebase.iid.FirebaseInstanceId.zza(com.google.firebase:firebase-iid@@20.1.4:51)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at com.google.firebase.iid.FirebaseInstanceId.getToken(com.google.firebase:firebase-iid@@20.1.4:87)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at com.hoxfon.react.RNTwilioVoice.TwilioVoiceModule.registerForCallInvites(TwilioVoiceModule.java:543)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at com.hoxfon.react.RNTwilioVoice.TwilioVoiceModule.initWithAccessToken(TwilioVoiceModule.java:507)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:873)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:193)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
03-30 20:43:22.782  7622  7775 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764)
```

Could this be because of a dependency update? I see `com.google.firebase:firebase-iid@@20.1.4`, but I don't believe that's been officially released. Any help would be greatly appreciated. This started happening today.

**Comment by TheRohitSharma** [comment]
Here's a list of updates from just yesterday: https://firebase.google.com/support/release-notes/android#2020-03-30

This one specifically: https://firebase.google.com/support/release-notes/android#iid_v20-1-3

> FirebaseApp now requires a non-empty project ID set in the corresponding FirebaseOptions.

It looks like this is causing the error.

**Comment by TheRohitSharma** [comment]
Never mind. Fixed this by adding `force = true` in my build.gradle for firebase-messaging. Closing.
