### ISSUE TITLE
Impossible to re-try to connect a call after Authorization error

### ISSUE THREAD

**Issue by fabriziomoscon** [hoxfon/react-native-twilio-programmable-voice#19]
RN 0.43.4
react-native-twilio-programmable-voice 0.6.1
Android emulator 7.0.0

When I try to re-connect an outgoing call after receiving an `Authorization error` I received another error: `Wrong answer from a service`. Also the `RegistrationListener().onRegistered()` method is called multiple times.

This is the exception: `sending message to a Handler on a dead thread`

```bash
E/TwilioVoice: outgoingCallListener onDisconnected error: 31201, Authorization error
D/TwilioVoice: sendEvent connectionDidDisconnect params { NativeMap: {"err":"Authorization error","call_state":"DISCONNECTED","call_sid":null} }
D/TwilioVoice: sendEvent deviceReady params null
D/TwilioVoice: sendEvent deviceReady params null
D/TwilioVoice: connect params: { NativeMap: {"CallerId":"+441253530539","To":"+441992351888"} }
W/MessageQueue: Handler (android.os.Handler) {cd9baba} sending message to a Handler on a dead thread
      java.lang.IllegalStateException: Handler (android.os.Handler) {cd9baba} sending message to a Handler on a dead thread
          at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
          at android.os.Handler.enqueueMessage(Handler.java:643)
          at android.os.Handler.sendMessageAtTime(Handler.java:612)
          at android.os.Handler.sendMessageDelayed(Handler.java:582)
          at android.os.Handler.post(Handler.java:338)
          at com.twilio.voice.CallCommandHandlerImpl.postCommand(CallCommandHandlerImpl.java:34)
          at com.twilio.voice.CallControlManager.call(CallControlManager.java:364)
          at com.twilio.voice.VoiceClient.call(VoiceClient.java:121)
          at com.hoxfon.react.TwilioVoice.TwilioVoiceModule.connect(TwilioVoiceModule.java:588)
          at java.lang.reflect.Method.invoke(Native Method)
          at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
          at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:141)
          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
          at android.os.Handler.handleCallback(Handler.java:751)
          at android.os.Handler.dispatchMessage(Handler.java:95)
          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
          at android.os.Looper.loop(Looper.java:154)
          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
          at java.lang.Thread.run(Thread.java:761)
D/TwilioVoice: sendEvent deviceReady params null
E/TwilioVoice: Error: 31404, Wrong answer from a service
D/TwilioVoice: sendEvent deviceNotReady params { NativeMap: {"err":"Wrong answer from a service"} }
D/TwilioVoice: sendEvent deviceReady params null
```

When I wait 2 seconds before retrying the call the error disappear and the call is connected

**Comment by fabriziomoscon** [comment]
fixed in #164
