### ISSUE TITLE
Crash when checking google play service availability and 9.8 is installed

### ISSUE THREAD

**Issue by fabriziomoscon** [hoxfon/react-native-twilio-programmable-voice#2]
RN 0.38
this lib 0.2.2
Android 5.1.1 and 7.0.0
Google play service: 

```
Exception in native call
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
     at com.google.android.gms.common.GoogleApiAvailability.zza(Unknown Source)
     at com.google.android.gms.common.GoogleApiAvailability.getErrorDialog(Unknown Source)
     at com.google.android.gms.common.GoogleApiAvailability.getErrorDialog(Unknown Source)
     at com.hoxfon.react.TwilioVoice.TwilioVoiceModule.checkPlayServices(TwilioVoiceModule.java:678)
     at com.hoxfon.react.TwilioVoice.TwilioVoiceModule.startGCMRegistration(TwilioVoiceModule.java:168)
     at com.hoxfon.react.TwilioVoice.TwilioVoiceModule.<init>(TwilioVoiceModule.java:138)
     at com.hoxfon.react.TwilioVoice.TwilioVoicePackage.createNativeModules(TwilioVoicePackage.java:28)
     at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:954)
     at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:878)
     at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
     at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
     at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
```

**Comment by dabit3** [comment]
@fabriziomoscon I'm getting this same issue. Any ideas what may be causing it?

**Comment by dabit3** [comment]
I think this error was being thrown because Google Play services was not installed on my emulator (in my case, Genymotion). [This Stackoverflow issue](http://stackoverflow.com/questions/20121883/how-to-install-google-play-services-in-a-genymotion-vm-with-no-drag-and-drop-su) helped me fix this for anyone that may be coming here.

**Comment by fabriziomoscon** [comment]
@dabit3 yes I logged the issue, and I wasn't able to reproduce it once I have upgraded Googl ePlay Service. The solution is installing/upgrading Google Play Service on the device.

But doing so prevented my from debugging further. We should see if somebody has further help here. It might be a small corner case though.
