### ISSUE TITLE
 Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by tragicmj** [hoxfon/react-native-twilio-programmable-voice#222]
Did you follow all the instructions as specified in the Twilio Quickstart repositories?
YES

What version of React Native are you running?
0.66.1

What version of react-native-twilio-programmable-voice are you running?
SDK 5

What device are you using? (e.g iOS10 simulator, Android 7 device)?
Any Android Device with Android Version 13

Is your app running in foreground, background or not running?
Foreground

Is there any relevant message in the log?
```
java.lang.IllegalArgumentException: com.myapp.android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
    at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
    at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:491)
    at android.app.PendingIntent.getActivity(PendingIntent.java:477)
    at android.app.PendingIntent.getActivity(PendingIntent.java:441)
    at com.hoxfon.react.RNTwilioVoice.CallNotificationManager.createHangupNotification(CallNotificationManager.java:154)
    at com.hoxfon.react.RNTwilioVoice.TwilioVoiceModule$3.onConnected(TwilioVoiceModule.java:309)
    at com.twilio.voice.Call$1$2.run(Call.java:641)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:1012)
```
Step to reproduce
1. Try placing call on android 13 device

Advanced:
can share a project with issue?
No

Is anybody else also going through the same problem??  Have tried the below code as per stackoverflow but still seeing the issue

```
 implementation 'androidx.work:work-runtime:2.7.1' //androidx.work:work-runtime:2.7.0-alpha05
 implementation 'androidx.work:work-runtime-ktx:2.7.1' 
    configurations.all {
        resolutionStrategy { 
            force 'androidx.work:work-runtime:2.7.1'
            force 'androidx.work:work-runtime-ktx:2.7.1' 
        }
    }
```

**Comment by tragicmj** [comment]
@fabriziomoscon can you or any other of the contributors look into it and other issues. There are a lot of them open.
