### ISSUE TITLE
Crash on createIncomingCallNotification on Android

### ISSUE THREAD

**Issue by mahyarr** [hoxfon/react-native-twilio-programmable-voice#87]
First of all, thanks for this great library.

I'm trying to integrate this package in my project, and right now I'm at a stage where I can successfully register the device with Twilio but when I receive a call, I get the following error:

```
java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/xxxx-8_oCGIg2mbtRfvb2BjaNCw==/base.apk:classes2.dex)
        at com.hoxfon.react.RNTwilioVoice.CallNotificationManager.createIncomingCallNotification(CallNotificationManager.java:140)
        at com.hoxfon.react.RNTwilioVoice.fcm.VoiceFirebaseMessagingService.showNotification(VoiceFirebaseMessagingService.java:165)
        at com.hoxfon.react.RNTwilioVoice.fcm.VoiceFirebaseMessagingService.handleIncomingCall(VoiceFirebaseMessagingService.java:138)
        at com.hoxfon.react.RNTwilioVoice.fcm.VoiceFirebaseMessagingService.access$100(VoiceFirebaseMessagingService.java:36)
        at com.hoxfon.react.RNTwilioVoice.fcm.VoiceFirebaseMessagingService$1$1$1.onReactContextInitialized(VoiceFirebaseMessagingService.java:107)
        at com.facebook.react.ReactInstanceManager$6.run(ReactInstanceManager.java:984)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
```

Any idea how I can resolve this?

--------
react-native: 0.55.4
react-native-twilio-programmable-voice: 3.18.1
Device: Android 7
App running in foreground

**Comment by mahyarr** [comment]
Ok I fixed this one. The problem was I had the following code at the end of my build.gradle file

```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.4.0'
            }
        }
    }
}
```

And I had to change the version from '25.4.0' to '26.0.0'.
